name: 'Run Unit Tests'
description: 'Run unit tests with coverage for the Go application'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.26'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
      with:
        go-version: ${{ inputs.go-version }}

    - name: Check action inputs
      shell: bash
      run: go run .github/scripts/check_inputs.go

    - name: Run unit tests with coverage
      shell: bash
      run: make test-with-coverage
