name: 'PR Slack Reminders'
description: 'Sends Slack reminders about open and stale PRs'
inputs: {
  github-token: {
    description: 'GitHub token to access the repository',
    required: false,
  },
  slack-bot-token: {
    description: 'Slack bot token to send the message via (the bot must be a member of the channel)',
    required: true,
  },
  slack-channel-name: {
    description: 'Slack channel name to send the message to',
    required: false,
  },
  slack-channel-id: {
    description: 'Slack channel ID to send the message to',
    required: false,
  },
  github-user-slack-user-id-mapping: {
    description: 'Mapping of GitHub usernames to Slack user IDs (e.g., "alice: U08RWPGNCUX\\nbob: U08RWPGNWER")',
    required: false,
  }
}

runs:
  using: 'node22'
  main: 'invoke-binary.js'
