name: 'PR Slack Reminders'
description: 'Sends Slack reminders about open and stale PRs'
inputs: {
  slack-bot-token: {
    description: 'Slack bot token to send the message via (the bot must be a member of the channel)',
    required: true,
  },
  channel-name: {
    description: 'Slack channel name to send the message to',
    required: false,
  },
  channel-id: {
    description: 'Slack channel ID to send the message to',
    required: false,
  },
  github-user-slack-user-id-mapping: {
    description: 'Mapping of GitHub usernames to Slack user IDs (e.g., "alice: U08RWPGNCUX\\nbob: U08RWPGNWER")',
    required: false,
  }
}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - run: go run ./cmd/pr-slack-reminder
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL_NAME: ${{ inputs.channel-name }}
        SLACK_USER_IDS_BY_GITHUB_USERS: ${{ inputs.github-user-slack-user-id-mapping }}
