name: 'PR Slack Reminder'
description: 'Sends a Slack reminder about open and stale PRs'
inputs: {
  github-token: {
    description: 'GitHub token to access the repository',
    required: true,
  },
  slack-bot-token: {
    description: 'Slack bot token to send the message via (the bot must be a member of the channel)',
    required: true,
  },
  slack-channel-name: {
    description: 'Slack channel name to send the message to',
    required: true,
  },
  slack-channel-id: {
    description: 'Slack channel ID to send the message to',
    required: false,
  },
  github-user-slack-user-id-mapping: {
    description: 'Mapping of GitHub usernames to Slack user IDs (e.g., "alice: U08RWPGNCUX\\nbob: U08RWPGNWER")',
    required: false,
  },
  main-list-heading: {
    description: 'Main heading of the message to send',
    required: false,
    default: 'There are <pr_count> open PRs 🚀',
  },
  old-prs-list-heading: {
    description: 'Heading for the list of old PRs (right under the main heading)',
    required: false,
  },
  no-prs-message: {
    description: 'Message to send when there are no open PRs',
    required: false,
  }
}

runs:
  using: 'node20'
  main: 'invoke-binary.js'
