name: 'Run Lint & Unit Tests'
description: 'Run static checks and unit tests with coverage for the Go application'
  
runs:
  using: composite
  steps:
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7.0.0
      with:
        go-version-file: go.mod

    - name: Check action inputs
      shell: bash
      run: go run .github/scripts/check_inputs.go

    - name: Check formatting
      shell: bash
      run: make check-fmt

    - name: Check vet
      shell: bash
      run: make check-vet

    - name: Run unit tests with coverage
      shell: bash
      run: make test-with-coverage

    - name: Check dead code
      shell: bash
      run: make check-dead-code

    - name: Check vulnerabilities
      shell: bash
      run: make check-vulnerabilities
