name: Build & Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Whether to bump major, minor, or patch version'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  contents: write

jobs:
  build-and-release:
    name: build & tag release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: make build-all

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit built binary
        run: |
          git add invoke-binary.js dist/
          git status
          git commit -m "Update action executables" || echo "No changes to commit"
          git push
