name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run unit tests
        run: go test ./...

  dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
   
    steps:
      - uses: actions/checkout@v4
      - uses: ./        
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-bot-token: ${{ secrets.DEV_SLACK_TOKEN }}
          slack-channel-name: 'pr-reminders-test'
