name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'dist/**'
      - 'invoke-binary.js'
  pull_request:
    branches: [main]

jobs:
  unit-tests-and-build:
    name: Unit Tests & Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Check action inputs
        run: go run .github/scripts/check_inputs.go

      - name: Run unit tests
        run: make test-with-coverage
        
      - name: Build
        run: make build-linux-amd64
        
      - name: Install goveralls # for coverage reporting
        run: go install github.com/mattn/goveralls@v0.0.12
      
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: make publish-code-coverage
