name: E2E Test Run

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'dist/**'
      - 'invoke-binary.js'

jobs:  
 test-run:
    name: Test Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
   
    steps:
      - uses: actions/checkout@v4
      - uses: ./        
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-bot-token: ${{ secrets.DEV_SLACK_TOKEN }}
          slack-channel-name: 'pr-reminders-test'
          github-user-slack-user-id-mapping: |
            hellej: U08SZJTJF0U
            bob: U08EVPGNWER
