name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests-and-build:
    name: Unit Tests & Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run unit tests
        run: make test-with-coverage

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@v0.0.12
      
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: make publish-code-coverage

      - name: Calculate and display total coverage
        id: coverage_total
        run: |
          echo "TOTAL_COVERAGE=$(go tool cover -func=coverage.out | grep '^total:' | awk '{print $NF}')" >> $GITHUB_OUTPUT
          go tool cover -func=coverage.out

      - name: Print Total Coverage (for verification)
        run: |
          echo "Overall project coverage: ${{ steps.coverage_total.outputs.TOTAL_COVERAGE }}"

      - name: Build
        run: make build-linux-amd64
